services:
  nginx-proxy:
    image: nginx:latest
    container_name: web-exchank-proxy
    ports:
      - "80:80"
    volumes:
      - /home/gool/PROJACT/Web-Exchang-Font-End-REACT/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always 

  db:
    image: postgres:16-alpine
    container_name: web-exchank-db-dev
    # พระเอกของเรา บังคับการเข้ารหัสตั้งแต่ Server สตาร์ท
    command: ["postgres", "-c", "password_encryption=scram-sha-256"]
    ports:
      - "127.0.0.1:5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_exchank
      TZ: Asia/Bangkok
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: web-exchank-redis-dev
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data_dev:/data 
    restart: unless-stopped

volumes:
  postgres_data_dev:
    name: web-exchang-back-end-nestjs_postgres_data_dev
  redis_data_dev:
    name: web-exchang-back-end-nestjs_redis_data_dev
