server {
    listen 80;
    server_name _ nattawooth.space; # Default server name to catch all requests

    # --- 1. ส่วนของ Frontend: หน้าที่ทำเสร็จแล้ว (Static) ---
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # --- 2. ส่วนของ Backend API (NestJS) ---
    # จะถูกเรียกผ่าน http://<IP>/api/...s
    location /api/ {
        # ชี้ไปที่เครื่องที่รัน NestJS
        proxy_pass http://host.docker.internal:3002/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # ส่งผ่าน Cookie สำคัญมากสำหรับระบบออเทนแบบคุกกี้
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
    }


}
server {
    listen 80;
    server_name div.nattawooth.space; # ตั้งชื่อ subdomain ที่ต้องการ

    location / {
        proxy_pass http://host.docker.internal:5173; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
        # --- 2. ส่วนของ Backend API (NestJS) ---
    # จะถูกเรียกผ่าน http://<IP>/api/...s
    location /api/ {
        # ชี้ไปที่เครื่องที่รัน NestJS
        proxy_pass http://host.docker.internal:3002/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # ส่งผ่าน Cookie สำคัญมากสำหรับระบบออเทนแบบคุกกี้
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
    }
}
